---
# the main tasks file for headless-raspi-config-ansible
- name: First perform `apt-get update` and `apt-get upgrade`
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install the required RPi packages for media playback
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ headless_raspi_config_pi_required_packages }}"

- name: Configure several `raspi_config nonint` settings in series
  ansible.builtin.include_tasks: raspi_config.yml
  loop:
    # Set up timezone to match your location
    - { raspi_config_nonint_cmd: 'do_change_timezone', cmd_argument: "{{ headless_raspi_config_pi_timezone }}" }
    # Set up language and regional settings to match your location
    - { raspi_config_nonint_cmd: 'do_change_locale', cmd_argument: "{{ headless_raspi_config_pi_locale_setting }}" }
    # Set the keyboard layout to match your keyboard
    - { raspi_config_nonint_cmd: 'do_configure_keyboard', cmd_argument: "{{ headless_raspi_config_pi_keyboard_layout }}" }
    # Set the hostname
    - { raspi_config_nonint_cmd: 'do_hostname', cmd_argument: "{{ headless_raspi_config_pi_hostname }}" }
    # Enabling autologin at the command-line console upon booting up
    - { raspi_config_nonint_cmd: 'do_boot_behaviour', cmd_argument: "{{ headless_raspi_config_pi_bootup_behavior }}" }

- name: Attempting to disable experimental desktop GL driver (using original legacy non-GL desktop driver)
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: "{{ item.pattern }}"
    line: "{{ item.new_string }}"
  loop:
    - { pattern: '^dtoverlay=vc4-fkms-v3d', new_string: '#dtoverlay=vc4-fkms-v3d' }
    - { pattern: '^dtoverlay=vc4-kms-v3d', new_string: '#dtoverlay=vc4-kms-v3d' }
  notify: Restart RPi

- name: Enabling Glamor graphics hardware acceleration if possible
  ansible.builtin.command: raspi-config nonint do_glamor 1
  changed_when: true
  notify: Restart RPi

- name: Ensures that all of the SD card storage is available to the OS
  ansible.builtin.command: raspi-config --expand-rootfs
  changed_when: true
  notify: Restart RPi
